---

- name: Make Directory for handson
  file:
    path: /home/ec2-user/handson
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Copy Sample Playbook
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: ec2-user
    group: ec2-user
    mode: 0644
  loop: "{{ sample_playbook }}"