AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  VolumeSize:
    Type: Number
  ImageId:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  GroupSet:
    Type: List<String>
  Name:
    Type: String
Resources:
  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: !Ref VolumeSize
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      InstanceType: !Ref InstanceType
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SubnetId
          GroupSet: !Ref GroupSet
      Tags:
          - Key: Name
            Value: !Ref Name