---

- name: create a cloudformation stack
  cloudformation:
    stack_name: "{{ item }}"
    state: present
    region: ap-northeast-1
    template: roles/create_ec2instance/files/ec2.yml
    template_parameters:
      KeyName: "{{ keyname }}"
      VolumeSize: "{{ volumesize }}"
      ImageId: "{{ imageid }}"
      InstanceType: "{{ instancetype }}"
      SubnetId: "{{ subnetid }}"
      GroupSet: "{{ groupset }}"
      Name: "{{ nametag }}"
  with_sequence: "start=1 end={{ howmany }} format=Ansible-Master%02d"

