# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.9.15 ansible-lint==4.3
      - name: Ansible-Lint
        run: |
          ansible-playbook create_env.yml --syntax-check
          ansible-playbook setup_env.yml --syntax-check
          ansible-playbook test_scenario.yml --syntax-check
          ansible-playbook delete_env.yml --syntax-check
          ansible-lint -x 301 -x 305 --force-color
